---
title: "Overview"
---
ProntoPCR is a software application that aims to perform routine qPCR calculations efficiently and automatically, such as averaging the housekeeper genes, calculating ΔCq, ΔΔCq, relative fold-change (2^-ΔCq), and fold-change (2^-ΔΔCq) of the target gene. It also provides the user with options to perform statistics and graphing of the data. ProntoPCR is an open-source, R shiny (Chang et al., 2024) software application available both online and locally as an R package (R Core Team., 2013), making it accessible to users with minimal programming experience. It is also designed to be compatible with the output generated by PCR machines, such as the Quantstudio 5 (Thermo Fisher Scientific) enabling the user to get instant results. Users only require a comma separated values (.csv) file of the raw data, including the quantification cycle (Cq) values, the target (gene) and sample name to get started. 


We request that users of ProntoPCR cite the associated journal article if the application has been used in analysis. The citation is as follows:

<br><br>

# Instructions for Use

ProntoPCR has been designed to operate both online and locally. While we aim to maintain online availability, the hosted platform may change or become unavailable. Note the online application times out after 5 minutes of inactivity. Therefore, it is recommended to rely on the local version, which functions with the same features as the online option. The local version also does not require internet access once installed.


To run the application locally, the user needs to download R: https://cran.r-project.org/ and RStudio: https://posit.co/downloads/. A step-by-step guide on how to install the ProntoPCR application locally can be found in the [Getting Started – Local Access](local_access.qmd) section. Online access instructions are available in the [Getting Started – Online Access](online_access.qmd) section. The guide is aimed at users with minimal programming expertise. If any instructions are unclear, please contact the developers.


