library(shiny)
library(shinytest)


app <- ShinyDriver$new(".")
app$snapshotInit("mytest")

app$setInputs(tabselected = "2")
app$takeScreenshot()
app$uploadFile(file = "exampledata.csv") # <-- This should be the path to the file, relative to the app's tests/shinytest directory
app$takeScreenshot()
app$setInputs(table_rows_current = c(1, 2, 3, 4, 5), allowInputNoBinding_ = TRUE, wait_ = FALSE, values_ = FALSE)
app$setInputs(table_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144), allowInputNoBinding_ = TRUE, wait_ = FALSE, values_ = FALSE)
app$setInputs(table_state = c(1711593743089, 0, 5, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(group1 = "PPIA")
app$takeScreenshot()
app$setInputs(group2 = "GAPDH")
app$setInputs(group3 = "B2M")
app$takeScreenshot()
app$setInputs(save_btn = "click")
app$snapshot()
app$setInputs(tabselected = "3", timeout_ = 80000)
app$takeScreenshot()
app$setInputs(calculations_table_rows_current = c(1, 2, 3, 4, 5), allowInputNoBinding_ = TRUE)
app$setInputs(calculations_table_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25), allowInputNoBinding_ = TRUE)
app$setInputs(calculations_table_state = c(1711593763870, 0, 5, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$setInputs(filtered_table_rows_current = c(1, 2, 3, 4, 5), allowInputNoBinding_ = TRUE)
app$setInputs(filtered_table_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10), allowInputNoBinding_ = TRUE)
app$setInputs(filtered_table_state = c(1711593763926, 0, 5, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$takeScreenshot()
app$setInputs(condition = "SC")
app$setInputs(filtered_table_rows_current = c(1, 2, 3, 4, 5), allowInputNoBinding_ = TRUE)
app$setInputs(filtered_table_rows_all = c(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15), allowInputNoBinding_ = TRUE)
app$setInputs(filtered_table_state = c(1711593767633, 0, 5, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshotDownload("download_processed_data-download")
app$snapshot()
app$setInputs(tabselected = "4")
app$setInputs(subStats = "2")
app$setInputs(sampleInput = "N_sample1")
app$setInputs(sampleInput = c("N_sample1", "SC_sample1"))
app$setInputs(sample_size = TRUE)
app$setInputs(nTable_rows_current = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(nTable_rows_all = c(1, 2), allowInputNoBinding_ = TRUE)
app$setInputs(nTable_state = c(1711593785473, 0, 5, "", TRUE, FALSE, TRUE, c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE), c(TRUE, "", TRUE, FALSE, TRUE)), allowInputNoBinding_ = TRUE)
app$snapshot()
app$setInputs(tabselected = "5")
app$setInputs(selected_condition = "N_sample1")
app$setInputs(selected_condition = c("N_sample1", "SC_sample1"))
app$setInputs(x_axis_positions = "N")
app$setInputs(x_axis_positions = "N_sample1")
app$setInputs(x_axis_positions = "N_sample1,")
app$setInputs(x_axis_positions = "N_sample1,SC")
app$setInputs(x_axis_positions = "N_sample1,SC_")
app$setInputs(x_axis_positions = "N_sample1,SC_s")
app$setInputs(x_axis_positions = "N_sample1,SC_sa")
app$setInputs(x_axis_positions = "N_sample1,SC_sample1")
app$setInputs(color_scheme_select = "oranges2")
app$snapshot()
